TARGET = absolute ascill big_etter grade multiplyTable one2tensum passFail posZeroNeg star cake sosu

all : ${TARGET}

absolute :
ascill : $@
big_etter : $@
grade : $@
multiplyTable : $@
one2tensum : $@
passFail : $@
posZeroNeg : $@
star : $@
cake : $@
sosu: $@
arithmetics : $@
clean:
	rm ${TARGET}